### ISSUE TITLE
calculate species goals 

### ISSUE THREAD

**Issue by DanWismer** [NCC-CNC/wtw-data-prep#23]
Calculate goals using the Rodriguez method.

This function was previously used for `wheretowork-input-formatting`. Goals were mostly being set to 100% because we weren't considering the entire species range. I will need to modify this function using data from the `Species_Metadata.xlsx`, a product of `wtw-species-prep`.

```
calculate_targets <- function(x, minimum_range_size = 1000,
                              proportion_at_minimum_range_size = 1,
                              maximum_range_size = 250000,
                              proportion_at_maximum_range_size = 0.1,
                              cap_range_size = 10000000,
                              cap_target_amount = 1000000) {
  # initialization
  out <- rep(NA_real_, length(x))
  pos <- which(is.finite(x))
  # set targets below threshold
  out[pos] <- stats::approx(
    x = log10(c(minimum_range_size, maximum_range_size)),
    y = c(proportion_at_minimum_range_size,
          proportion_at_maximum_range_size),
    xout = log10(x[pos]), method = "linear", rule = 2)$y
  # set caps
  cap_pos <- which(x > cap_range_size)
  if (length(cap_pos) > 0) {
    out[cap_pos] <- cap_target_amount / x[cap_pos]
  }
  # return values
  return(out)
}

```

**Comment by DanWismer** [comment]
I updated `04_populate_nat_metadata.R` to include the Rodrigues method (scaled). 

@ricschuster and @edwardsmarc, could you give this a look? I still get goals for most features being 100%. I can't find what I am doing wrong ... 

Metadata:
[sw-on-v2-metadata-NEEDS-QC.csv](https://github.com/NCC-CNC/wtw-data-prep/files/12432923/sw-on-v2-metadata-NEEDS-QC.csv)

Script:
https://github.com/NCC-CNC/wtw-data-prep/blob/e07571feeb5ab3e036b22230f16fe5fb4430137b/scripts/04_populate_nat_metadata.R#L298-L312

Function:
https://github.com/NCC-CNC/wtw-data-prep/blob/23-goals-rodriguez/scripts/functions/fct_calculate_targets.R

**Comment by DanWismer** [comment]
... is `x` the sum of the clipped habitat/range (AOI)? Or rather `x` is the sum of the entire species habitat/range (Canada)?

**Comment by edwardsmarc** [comment]
> ... is `x` the sum of the clipped habitat/range (AOI)? Or rather `x` is the sum of the entire species habitat/range (Canada)?

Entire species! I think that's what's going wrong.

When I ran this for the Grassland analysis I used `calculate_targets()` on the national sums that you had in your excel sheet. That returns a set of proportions which I joined to the meta data table. I then passed the proportions as the goals to use in prioritizr.

I'll copy my code below:

```
library(readr)
library(readxl)
library(purrr)
library(dplyr)

# Note cap_range size dropped from 10,000,000 to 1,000,000 and cap_target_amount 
# dropped from 1,000,000 to 100,000 based on email to Dan from Sahebeh

# Note the code to do this directly in prioritizr is: add_loglinear_targets(1000,1,250000,0.1,1000000,100000)
calc_goals <- function(x, 
                       minimum_range_size = 1000, proportion_at_minimum_range_size = 1, 
                       maximum_range_size = 250000, proportion_at_maximum_range_size = 0.1, 
                       cap_range_size = 1000000, cap_target_amount = 100000) {
  # initialization
  out <- rep(NA_real_, length(x))
  pos <- which(is.finite(x))
  
  # set targets below threshold
  out[pos] <- stats::approx(
    x = log10(c(minimum_range_size, maximum_range_size)),
    y = c(proportion_at_minimum_range_size,
          proportion_at_maximum_range_size),
    xout = log10(x[pos]), method = "linear", rule = 2)$y
  
  # set caps
  cap_pos <- which(x > cap_range_size)
  if (length(cap_pos) > 0) {
    out[cap_pos] <- cap_target_amount / x[cap_pos]
  }
  
  # return values
  return(out)
}

################################################################################

### Add Rodrigues goals to species meta data

# Open data sheet from Dan
f <- "../gisdata/WTW_NAT_SPECIES_METADATA.xlsx"
df <- f |>
        excel_sheets() |>
        set_names() |>
        purrr::map(read_excel, path = f) |>
        list_rbind()
df <- df |> dplyr::select(File, Total_Km2)

df$Rodgrigues <- calc_goals(df$Total_Km2)
hist(df$Rodgrigues)

# of 6140 species, this results in:
# 100% Goal: 3689
# 50-100% Goal: 1617
# 0-50% Goal: 834

### Join goals to species in meta data
meta <- read_csv("./WTW/metadata/weston_grassland-metadata-NEEDS-QC.csv")

meta <- left_join(x = meta, y = df, by = "File")
meta$Goal <- meta$Rodgrigues
write_csv(meta, "./WTW/metadata/weston_grassland-metadata-NEEDS-QC.csv")
```

The histogram of targets looks like this. The first bar represents species with large ranges that get capped at 1,000,000. Then you get an increase in the bars going to right which matches the distribution of species range sizes (more species with small ranges).

![image](https://github.com/NCC-CNC/wtw-data-prep/assets/10728298/65d91671-bff4-4141-be54-1274e90b69ba)

**Comment by DanWismer** [comment]
Excellent, thanks @edwardsmarc, I will make that change.

I suppose the goals can be calculated when I build the SPECIES_METADATA sheets (a new goals column). For now I will calculate them on the fly

**Comment by edwardsmarc** [comment]
> Excellent, thanks @edwardsmarc, I will make that change.
> 
> I suppose the goals can be calculated when I build the SPECIES_METADATA sheets (a new goals column). For now I will calculate them on the fly

Yeah it would be great to have those goals saved along with the species meta data. Then we can just pull them in to other workflows without having to rerun the code.

**Comment by DanWismer** [comment]
Sounds good, I will update https://github.com/NCC-CNC/wtw-species-prep/blob/main/R/species_metadata.R to include the Rodrigues goals.

**Comment by DanWismer** [comment]
@edwardsmarc, when you have a chance, can you look over these goals and see if they agree with what you came up with?
[WTW_NAT_SPECIES_METADATA_NEEDSQC.xlsx](https://github.com/NCC-CNC/wtw-data-prep/files/12433795/WTW_NAT_SPECIES_METADATA_NEEDSQC.xlsx)

**Comment by edwardsmarc** [comment]
> @edwardsmarc, when you have a chance, can you look over these goals and see if they agree with what you came up with? [WTW_NAT_SPECIES_METADATA_NEEDSQC.xlsx](https://github.com/NCC-CNC/wtw-data-prep/files/12433795/WTW_NAT_SPECIES_METADATA_NEEDSQC.xlsx)

Yes! These match exactly with what I calculated.

**Comment by DanWismer** [comment]
Excellent.

hmm, I used the Rodrigues goals for SW-ON example and when you do a default run, it selects the entire AOI:
![image](https://github.com/NCC-CNC/wtw-data-prep/assets/29556279/34aa1ff8-e35b-48ea-826e-d59edd7130d7)

I am thinking this is mainly because the AOI is small. Attached are the WTW import files to test. One idea is we can set a "greater then" threshold the AOI needs to pass in order to pull the Rodrigues goals? However that would mess up the fact WTW handles all the accounting.
  
[WTW.zip](https://github.com/NCC-CNC/wtw-data-prep/files/12440774/WTW.zip)

**Comment by ricschuster** [comment]
> Excellent.
> 
> hmm, I used the Rodrigues goals for SW-ON example and when you do a default run, it selects the entire AOI: ![image](https://user-images.githubusercontent.com/29556279/263307155-34aa1ff8-e35b-48ea-826e-d59edd7130d7.png)
> 
> I am thinking this is mainly because the AOI is small. Attached are the WTW import files to test. One idea is we can set a "greater then" threshold the AOI needs to pass in order to pull the Rodrigues goals? However that would mess up the fact WTW handles all the accounting.
> 
> [WTW.zip](https://github.com/NCC-CNC/wtw-data-prep/files/12440774/WTW.zip)

Did you calcualte the goals based on SW-ON data or based on national data? We would need to use the goals from national data to avoid choosing the entire AOI.

**Comment by DanWismer** [comment]
I pull the pre-calculated Rodrigues goals that were calculated nationally (line 308):

https://github.com/NCC-CNC/wtw-data-prep/blob/f49b5f3ef2f56ef4d511901d99abce8217bb2d0b/scripts/04_populate_nat_metadata.R#L298-L314

**Comment by edwardsmarc** [comment]
> I changed all the Theme tabs to "single" and I get this output now: ![image](https://user-images.githubusercontent.com/29556279/263314495-3c7ab432-7f7c-46d7-a793-677052be7fa2.png)

I just figured out the same thing. If you leave the tabs on the group option it sets all species in the Theme to 100% which explains why the entire AOI gets selected. If you open all the 'single' tabs it applies the species level goals correctly.

I wasn't previously aware of this behavior.

**Comment by ricschuster** [comment]
> > I changed all the Theme tabs to "single" and I get this output now: ![image](https://user-images.githubusercontent.com/29556279/263314495-3c7ab432-7f7c-46d7-a793-677052be7fa2.png)
> 
> I just figured out the same thing. If you leave the tabs on the group option it sets all species in the Theme to 100% which explains why the entire AOI gets selected. If you open all the 'single' tabs it applies the species level goals correctly.
> 
> I wasn't previously aware of this behavior.

Interesting. That behavior should be changed. We don't want that to happen.

**Comment by edwardsmarc** [comment]
> > > I changed all the Theme tabs to "single" and I get this output now: ![image](https://user-images.githubusercontent.com/29556279/263314495-3c7ab432-7f7c-46d7-a793-677052be7fa2.png)
> > 
> > 
> > I just figured out the same thing. If you leave the tabs on the group option it sets all species in the Theme to 100% which explains why the entire AOI gets selected. If you open all the 'single' tabs it applies the species level goals correctly.
> > I wasn't previously aware of this behavior.
> 
> Interesting. That behavior should be changed. We don't want that to happen.

I guess it makes sense, whichever tab you have open is how the goals get applied. But I'd rather have a switch next to each theme that greys out all the sliders in the 'group' or 'single' so it's really clear which goals are being used. To me, clicking on a tab is way to view information, I don't usually expect that to change the tool paramters.

**Comment by DanWismer** [comment]
A simple fix would be to flip them around; have it go in the order of "single" then "group", and the single tab would be activated on init.

**Comment by edwardsmarc** [comment]
> A simple fix would be to flip them around; have it go in the order of "single" then "group", and the single tab would be activated on init.

I think that would be a good start. I would consider changing the default for the group slider too. Maybe it just always starts at 0, or 20. That way it's clearer that the user needs to change it to something meaningful. I think I was thrown off because all the group sliders were auto-set to different values based on the species goals.
