### ISSUE TITLE
proposed data folder names

### ISSUE THREAD

**Issue by DanWismer** [NCC-CNC/wtw-data-prep#24]
Rename root data folder to: `WTW_NAT_DATA_YYYYMMDD`.

Then unest to only have one level:
![image](https://github.com/NCC-CNC/wtw-data-prep/assets/29556279/204b7c0c-f57d-45c1-ac4b-e04751334d24)

@edwardsmarc what do you think?

**Comment by edwardsmarc** [comment]
Fine by me. The data folder path is set by the user so any folder name should work.

What do you mean by 'unnest to only have one level'?

**Comment by DanWismer** [comment]
currently we have it like this: 
![image](https://github.com/NCC-CNC/wtw-data-prep/assets/29556279/f0b71563-241a-4fc5-85c3-0d8958b4c586)
 
 I'm thinking of taking everything out of the `national` folder so it looks like the 1st screen shoot, AND I believe I can delete the output and aoi folder

**Comment by edwardsmarc** [comment]
Ah OK, that makes sense to me. The aoi stuff is duplicated elsewhere anyway I think.

**Comment by DanWismer** [comment]
#24
