### ISSUE TITLE
split ECCC SAR and CH into threat level?

### ISSUE THREAD

**Issue by DanWismer** [NCC-CNC/wtw-data-prep#28]
@edwardsmarc @ricschuster 
Do we like this? I gave it a shot to see what it would look like in WTW. 

An alternative would be to keep it how it was before. One theme for ECCC SAR and another for ECCC CH; and on the label beside the species name, put the threat level (END, SPC, THR, etc.)?

**Comment by edwardsmarc** [comment]
@ricschuster FYI the Kejimkujik data I sent you uses this new Theme grouping.

I think this makes a lot of sense for goal setting where users might want to set a theme goal for all the species at a certain threat level.

On the flip side it adds more Themes to the display which can be a bit overwhelming, but I think it's worth it overall. I've actually been finding the meta data table useful for searching for specific species and figuring out what Theme they are in. @DanWismer I guess we could also use the SPECIES table for this once #27 is complete?

**Comment by DanWismer** [comment]
Thanks @edwardsmarc, good to know that splitting species by threat level has some value. In the short term, if themes need to be reconsolidate back, it would be easy enough to update the metadata.csv manually for that. And then run the final wtw format script.

**Comment by edwardsmarc** [comment]
> Thanks @edwardsmarc, good to know that splitting species by threat level has some value. In the short term, if themes need to be reconsolidate back, it would be easy enough to update the metadata.csv manually for that. And then run the final wtw format script.

Yeah I really like how easy it is to drop species or change the Theme groupings just by editing meta data. I just did that for Richard's data prep and it takes minutes to redo the WTW files.

**Comment by DanWismer** [comment]
Will close this questions, keeping the species split by threat for now
