### ISSUE TITLE
add prefix to script names: 01, 02, 03 etc. 

### ISSUE THREAD

**Issue by DanWismer** [NCC-CNC/wtw-data-prep#3]
- makes it more apparent which order to run the scripts

**Comment by edwardsmarc** [comment]
Any ideas for this given that not all of the scripts will be run in a given workflow?

e.g. a project using national data and the 1km grid would use:
- initiate_project.R
- aoi_to_1km_grid.R
- natdata_to_aoi_1km_grid.R
- populate_nat_metadata.R
- wtw_formatting.R

and a project using regional data and a custom grid would use:
- initiate_project.R
- aoi_to_custom_grid.R
- custom data prep scripts
- wtw_formatting.R


Something like this could work, but it might be confusing for some:
01_initiate_project.R
02_aoi_to_1km_grid.R
02_aoi_to_custom_grid.R
03_natdata_to_aoi_1km_grid.R
04_populate_nat_metadata.R
05_wtw_formatting.R

**Comment by DanWismer** [comment]
How about ...

01_initiate_project.R
02a_aoi_to_1km_grid.R 
02b_aoi_to_custom_grid.R
03_natdata_to_aoi_1km_grid.R
04_populate_nat_metadata.R
05_wtw_formatting.R

Then we can describe when to use 02a or 02b?

**Comment by edwardsmarc** [comment]
Yeah that makes sense. And we also make it explicit that you don't always need all the scripts.
