### ISSUE TITLE
new WTW_NAT_DATA folder structure

### ISSUE THREAD

**Issue by DanWismer** [NCC-CNC/wtw-data-prep#32]
The current structure I made last year and could be consolidated into something that captures both WTW and Landscape Resilience themes.

I am thinking of changing it to:
![image](https://github.com/NCC-CNC/wtw-data-prep/assets/29556279/db794153-7a7f-4199-b228-99030312c6a3)

Main reason is that I want to pull this folder to do the [resilience-data-prep](https://github.com/NCC-CNC/resilience-data-prep), and keeping things consistent will help in the long run. 

@edwardsmarc does this work for you?

**Comment by edwardsmarc** [comment]
Yeah I think this is a good idea. Go for it!
